framework:
    messenger:
        transports:
            async:
                dsn: "%env(RABBITMQ_URL)%"
                options:
                    auto_setup: true
        routing:
            # async is whatever name you gave your transport above
            'App\Message\WebpageContent': async
